### ISSUE TITLE
Time ago

### ISSUE THREAD

**Issue by simplesmiler** [simplesmiler/vue-requests#1]
A directive or component to display time since the timestamp.

Features:
- Refresh as time goes by
- Support Internationalization
- Support common time formats (unix seconds, unix milliseconds, ISO 8601)
- Support custom formatting

References:
- [nmn/react-timeago](https://github.com/nmn/react-timeago)
- [urish/angular-moment](https://github.com/urish/angular-moment) (`am-time-ago` directive)
- [yaru22/angular-timeago](https://github.com/yaru22/angular-timeago)
- [moment](https://github.com/moment/moment/) (i18n)

**Comment by veksen** [comment]
It would be great to support a level of precision. By default moment.js is limited to 1 level. 

1: 2 hours
2: 2 hours, 25 minutes
3: 2 hours, 24 minutes, 44 seconds

There is a [large discussion](https://github.com/moment/moment/issues/463) on the moment.js issues,
a [moment.js plugin](https://github.com/jsmreese/moment-duration-format) to extend functionalities,
and a [vue plugin](https://github.com/brockpetrie/vue-moment) for moment

**Comment by simplesmiler** [comment]
Closed with [vue-timeago](https://github.com/egoist/vue-timeago).
