### ISSUE TITLE
Input and textarea with autosize feature

### ISSUE THREAD

**Issue by simplesmiler** [simplesmiler/vue-requests#10]
There's a couple of different approaches.

The first one is to position the `input`/`textarea` absolutely inside of a `.container`, and place an invisible statically positioned `.ghost` alongside it, and make the `.ghost` content be synced with the `input`/`textarea`.

Another is to attach the `.ghost` element to the `body`, and use it to recalculate the proper size in `px` for the `input`/`textarea` whenever it's value changes. Multiple instances can share the same `.ghost`.

References:
- [Creating an Auto-Growing Text Input](http://www.brianchu.com/blog/2013/11/02/creating-an-auto-growing-text-input/) by Brian Chu
- [react-input-autosize](http://jedwatson.github.io/react-input-autosize/)
- [react-autosize-textarea](https://github.com/buildo/react-autosize-textarea)
- [autosize-input](https://github.com/yuanqing/autosize-input)
- [autosize](https://github.com/jackmoore/autosize)

**Comment by simplesmiler** [comment]
There is [vue-autosize-textarea](https://github.com/egoist/vue-autosize-textarea) by @egoist and [vue-autosize](https://github.com/mage3k/vue-autosize) by @mage3k, both for the textarea.

**Comment by paulpflug** [comment]
[vue-comps/vue-textarea](https://github.com/vue-comps/vue-textarea)

**Comment by chrisvfritz** [comment]
With the autosize npm package, implementing this feature is actually really trivial. [See here](https://github.com/lansingcodes/slide/blob/master/src/components/dynamic-invisible-textarea.vue#L41-L43) for an example.

**Comment by mesqueeb** [comment]
I would love Auto resize text area in Vue!
I've been looking at these links you guys gave, but none of them had clear instructions on how to install them... I'm still a newbie. >.>

**Comment by chrisvfritz** [comment]
@mesqueeb Here's a [simple example](https://jsfiddle.net/bjvmso23/) in action.

**Comment by syropian** [comment]
I put this together for text inputs (not textareas) today - https://github.com/syropian/vue-input-autosize

**Comment by warent** [comment]
@chrisvfritz doesn't work in my browser (Chrome 62.0.3202.94)

**Comment by chrisvfritz** [comment]
@warent That's because the example was written for Vue 1, but pinned to the latest version of Vue. I just updated the link and it should work now. 🙂

**Comment by chrisvfritz** [comment]
Since handling this use case without a dedicated Vue wrapper is so simple that Egoist even deprecated his package, I'm going to close this.

**Comment by warent** [comment]
For future reference to anyone else reading, I ended up using [mage3k/vue-autosize](https://github.com/mage3k/vue-autosize) and it works nicely.
