### ISSUE TITLE
v-dom-events, a directive that emits dom-enter and dom-leave events

### ISSUE THREAD

**Issue by simplesmiler** [simplesmiler/vue-requests#11]
A directive that emits custom events when element enters and leaves the DOM. Useful for reference counting and other memory-sensitive things, like integration with external libraries.

``` html
<div v-dom-events @dom-enter="enter" @dom-leave="leave">
  <div v-pre v-el:target></div>
</div>
```

``` js
module.exports = {
  enter: function() {
    $(this.$els.target).somePlugin();
  }),
  leave: function() {
    $(this.$els.target).somePlugin.destroy();
  }),
};
```

**Comment by paulpflug** [comment]
As I built a similar directive, I tried this one, but it isn't possible.
vue tears down all directives before the element leaves the dom (at least it is teared down the time mutationObserver fires an event)

I think you have to wrap the `somePlugin` in a component and use the `attached / detached` hook

**Comment by simplesmiler** [comment]
@paulpflug this is what I meant though. You generally want to tear down the plugin just before the element goes away.
I've used similar approach in angular app to count what things I need to keep in sync with the server. I worked great.

**Comment by paulpflug** [comment]
``` coffee
allCbs = []
evHandler = (e) ->
  for cb in allCbs
    cb(e)
observer = new MutationObserver evHandler
observer.observe document.body,
  childList: true
  subtree: true

module.exports = (Vue) ->
  Vue.directive "dom-events",
    bind: ->
      @currentEl = @el
      cb = (mr) =>
        for node in mr[0].addedNodes
          if node == @el
            console.log "enter" # works
        for node in mr[0].removedNodes
          if node == @el
            # will never print because @el is already null
            # and v-on will already be gone
            console.log "leave"
      allCbs.push cb
    update: ->
    unbind: ->
```

**Comment by simplesmiler** [comment]
I've actually been thinking something like the following (but with necessary ponyfills):

``` js
module.exports = {
  bind: function() {
    this.el.dispatchEvent(new CustomEvent('dom-enter'));
  },
  unbind: function() {
    this.el.dispatchEvent(new CustomEvent('dom-leave'));
  },
};
```

**Comment by paulpflug** [comment]
ouch^^ sometimes I'm just to stupid..

``` coffee
createEvent = (event, params) ->
  ce = window.CustomEvent
  unless ce?
    ce = (event, opt) ->
      opt = opt || bubbles: false, cancelable: false, detail: undefined
      evt = document.createEvent('CustomEvent')
      evt.initCustomEvent(event, opt.bubbles, opt.cancelable, opt.detail)
      return evt
    ce.prototype = window.Event.prototype
  return new ce(event,params)

module.exports = (Vue) ->
  Vue.directive "dom-events",
    bind: ->
      @el.dispatchEvent createEvent "enter"
    unbind: ->
      @el.dispatchEvent createEvent "leave"
```

I will upload it later..

**Comment by simplesmiler** [comment]
Offtopic: I noticed many people publish vue modules as plugins, and I'm not sure this is a good idea. This introduces implicit dependencies and opens the possibility for name clashes.

**Comment by paulpflug** [comment]
hm doesn't work yet.. v-on isn't there when bind is called and already gone when unbind is called. There was something about priority in the vue code..

**Comment by simplesmiler** [comment]
Priority should be about 600, IIRC.

**Comment by paulpflug** [comment]
yep, now it works. So you are against plugins.. ok i can do that ;)

**Comment by simplesmiler** [comment]
I'm not saying I'm against plugins, but I believe it's better to publish modules in such a way that consumer can decide whether he wants the directive/filter/etc be global or local.
I should really write my opinion on publishing vue bits and bobs in form of an article of whatnot.

**Comment by paulpflug** [comment]
https://github.com/paulpflug/vue-directives

**Comment by simplesmiler** [comment]
Cool beans :+1:
