### ISSUE TITLE
Office UI Fabric for Vue.js

### ISSUE THREAD

**Issue by kaorun343** [simplesmiler/vue-requests#22]
http://dev.office.com/fabric#/

**Comment by sotaan** [comment]
What should be the best option to port this:

- reimplementing from Angular / React version
- reviewing vanilla JS version and starting from scratch (almost)

**Comment by ismet** [comment]
I'm developing enterprise-level SharePoint apps using Vue.js, so Vueish Office UI Fabric is a must for me!

**Comment by kevyworks** [comment]
Link JS - https://dev.office.com/fabric-js

**Comment by kevinrodriguez-io** [comment]
Please do this

**Comment by kaorun343** [comment]
close this via https://github.com/vuejs/awesome-vue/pull/1606

**Comment by keschte** [comment]
I didnt make this, but this is pretty cool:
https://aidewoode.github.io/office-ui-fabric-vue/
