### ISSUE TITLE
Visual Search

### ISSUE THREAD

**Issue by stranger26** [simplesmiler/vue-requests#38]
A search bar with autocompleted parameters.

[Visual Search](http://documentcloud.github.io/visualsearch/)
[Angular Advanced Searchbox](http://dnauck.github.io/angular-advanced-searchbox/)

**Comment by probil** [comment]
It looks like vast majority of this functionality can be done using Vue-multiselect.
https://vue-multiselect.js.org/

**Comment by stranger26** [comment]
@probil Thank you for the recommendation!
