### ISSUE TITLE
Common utility functions

### ISSUE THREAD

**Issue by simplesmiler** [simplesmiler/vue-requests#5]
A module with common userland utility functions.

Features:
- [`escape`](https://github.com/simplesmiler/vue-requests/issues/5#issuecomment-183358291) filter for safe escaping text before further filtering (highlighting, nl2br)
- [`eventGuard`](https://github.com/simplesmiler/vue-requests/issues/5#issuecomment-183358553) filter for "consuming" events

**Comment by simplesmiler** [comment]
An `escape` filter is useful for things like highlighting and turning new lines into `<br`> without giving up safe escaping. It mimics default safe escaping so that `{{{ expr | escape }}}` is equal to `{{ expr }}`.

``` js
// @NOTE: vue templates are not string based, so there is no need to escape quotes and backslash
var entityRE = /[&<>]/g;
var entityMap = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
};

function escapeEntity(entity) {
  return entityMap[entity];
}

function escape(text) {
  return String(text).replace(entityRE, escapeEntity);
}
```

Usage: `{{{ text | escape | nl2br }}}` (note unsafe brackets).

**Comment by simplesmiler** [comment]
An `eventGuard` filter adds the "consume" logic (don't know the right term) to the event handler. Useful for avoiding boilerplate-wrapping of store actions and not cluttering your methods with event logic.

``` js
function eventGuard(handler) {
  return function(ev) {
    if (ev.defaultPrevented) return; // @NOTE: do nothing if event was already consumed
    ev.preventDefault(); // @NOTE: consume event

    handler();
  };
}
```

A filter that only ignores "consumed" events without "consuming" then may also be useful.
A filter that only "consumes" without ignoring does **not** seem to be useful

There is a vanilla `.prevent` modifier that is related, but filter seems to be more practical.

Usage: `@click="handler | eventGuard"`

**Comment by paulpflug** [comment]
regarding `eventGuard`. I haven't tested them but I think vue has this built in: [v-on modifieres](http://vuejs.org/api/#v-on)

Maybe we could create a package `vue-filters` similar to [vue-mixins](https://github.com/paulpflug/vue-mixins) where we collect filters

**Comment by simplesmiler** [comment]
@paulpflug the closest thing there is to `eventGuard` is `.self`, which is still not sufficient in some cases.

Here is a good read on the  subject: https://css-tricks.com/dangers-stopping-event-propagation/

**Comment by paulpflug** [comment]
thanks for the link. Interesting

I tried to integrate filters with vue-mixins, but they are not merged with the Vue component  
so I created [vue-filters](https://github.com/paulpflug/vue-filters)
currently has your `escape` and `nl2br` filter.

we have to work the name `eventGuard` and I think it would make sense to make 2 filters one with and one without consume.

**Comment by paulpflug** [comment]
I think the filter [here](http://forum.vuejs.org/topic/2001/using-filterby-with-multiple-searches-on-multiple-columns/2) is also useful, but needs a better name too

**Comment by simplesmiler** [comment]
Okay, let's move the discussion to [vue-filters](https://github.com/paulpflug/vue-filters) then.
