### ISSUE TITLE
Official server side rendering feature and Official Vue UI Widgets 

### ISSUE THREAD

**Issue by ansarizafar** [simplesmiler/vue-requests#8]
Server side rendering is very important for many use case and If Vue wants to compete with React and Angular2 then its a must have feature. Its nice to have an official Vue UI widgets library without Jquery dependency.

**Comment by simplesmiler** [comment]
Regarding SSR. Chances are the good SSR will not come from the inside, but rather it will come from the community and get adopted. There is currently [vue-server](https://github.com/ngsru/vue-server), and I believe Evan once said that Alibaba is working internally on something similar.

Regarding official UI. I don't think will happen. There are [vue-strap](https://github.com/yuche/vue-strap) and [vue-mdl](https://github.com/posva/vue-mdl) that seem to cover most people needs.

**Comment by YerkoPalma** [comment]
Vue 2.0 will come with SSR built-in, and there is a lot of UI components, just check vue-awesome and you'll get waht you want

**Comment by simplesmiler** [comment]
As @YerkoPalma said, SSR is coming.
